services:
  - type: web
    name: rag-docker
    env: docker
    plan: free
    docker:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: RAG_ENVIRONMENT
        value: production